version: '3'
services:
  web:
    container_name: demo-final
    image: nginx
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8091:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80